export const data = [{
    id: 1,
    designation: "Iphone X",
    fabricant: "Apple",
    categorie: "smartphone",
    prixTTC: 863,
    das: "0.98 W/kg",
    resolution: 5.8,
    batterie: "11h45",
    image: "img/iphonex.png",
    classeEnergie: "C",
    deee: 0.03,
    reyclable: "48%",
    note: 54
  },
  {
    id: 2,
    designation: "Huawei P20 Pro",
    fabricant: "Huawei",
    categorie: "smartphone",
    prixTTC: 1000,
    batterie: "50h",
    das: "0.4 W/kg",
    resolution: 6.39,
    image: "img/Smartphone-Huawei-Mate-20-Pro-Double-SIM-128-Go-Noir.jpg",
    deee: 0.02,
    classeEnergie: "A",
    recyclable: "50%",
    note: 72
  },
  {
    id: 3,
    designation: "Huawei P20 lite",
    fabricant: "Huawei",
    categorie: "smartphone",
    prixTTC: 250,
    batterie: "14h",
    das: "0.75 W/kg",
    resolution: 5.84,
    image: "img/HuaweiP20Pro.jpg",
    deee: 0.02,
    classeEnergie: "B",
    recyclable: "46%",
    note: 65
  },
  {
    id: 4,
    designation: "Galaxy Note 8 ",
    fabricant: "Samsung",
    categorie: "smartphone",
    prixTTC: 527,
    batterie: "9h",
    das: "0.173 W/kg",
    resolution: 5.2,
    image: "img/samsung-galaxy-note-8.jpg",
    deee: 0.02,
    classeEnergie: "B",
    recyclable: "58%",
    note: 70
  },
  {
    id: 5,
    designation: "Galaxy S9 double ",
    fabricant: "Samsung",
    categorie: "smartphone",
    prixTTC: 859,
    batterie: "12h",
    das: "0.362 W/kg",
    resolution: 5.68,
    image: "img/HuaweiP20Pro.jpg",
    deee: 0.02,
    classeEnergie: "C",
    recyclable: "48%",
    note: 48
  },
  {
    id: 6,
    designation: "Zenphone 6 ",
    fabricant: "Asus",
    categorie: "smartphone",
    prixTTC: 300,
    batterie: "22h",
    das: "0.58 W/kg",
    resolution: 4.24,
    image: "img/telephone-asus-zenfone-6-noir_4363_1.jpg",
    deee: 0.03,
    classeEnergie: "B",
    recyclable: "30%",
    note: 59
  },
  {
    id: 7,
    designation: "Mac Book Air 13 pouces ",
    fabricant: "Apple",
    categorie: "ordinateur",
    prixTTC: 1099,
    batterie: "12h",
    resolution: "1440 X 900",
    image: "img/HuaweiP20Pro.jpg",
    deee: 0.48,
    classeEnergie: "C",
    recyclable: "58%",
    note: 59
  },
  {
    id: 8,
    designation: "Mac Book Pro 13 pouces ",
    fabricant: "Apple",
    categorie: "ordinateur",
    prixTTC: 1499,
    batterie: "10h",
    resolution: "2560 X 1600",
    image: "img/HuaweiP20Pro.jpg",
    deee: 0.5,
    classeEnergie: "C",
    recyclable: "54%",
    note: 56
  },
  {
    id: 9,
    designation: "Lenovo T430s ",
    fabricant: "Lenovo",
    categorie: "ordinateur",
    prixTTC: 599,
    batterie: "6h",
    resolution: "1290 X 1080",
    image: "img/HuaweiP20Pro.jpg",
    deee: 0.041,
    classeEnergie: "D",
    recyclable: "49%",
    note: 59
  },
  {
    id: 10,
    designation: "ASUS S430UA-EB265T",
    fabricant: "Asus",
    categorie: "ordinateur",
    prixTTC: 1639.99,
    batterie: "12h",
    resolution: "2160 x 1440 ",
    image: "img/HuaweiP20Pro.jpg",
    deee: 1.01,
    classeEnergie: "B",
    recyclable: "52%",
    note: 62
  },
  {
    id: 11,
    designation: "Microsoft Surface Pro 3 ",
    fabricant: "Microsoft ",
    categorie: "ordinateur",
    prixTTC: 899,
    batterie: "10h",
    resolution: "2160 x 1440 ",
    image: "img/HuaweiP20Pro.jpg",
    deee: 0.3,
    classeEnergie: "B",
    recyclable: "54%",
    note: 70
  },

]