export const data = [{
    id: 1,
    designation: "Iphone X",
    fabricant: "Apple",
    categorie: "smartphone",
    prixTTC: 930,
    batterie: "12",
    image: "images/imageIphoneX.jpg",
    ondes: 20,
    deee: 0.2,
    classeEnergie: "A",
    label: "label1",
    note: 48
  },
  {
    id: 2,
    designation: "Huawei P20 Pro",
    fabricant: "Huawei",
    categorie: "smartphone",
    prixTTC: 850,
    batterie: "24",
    image: "images/HuaweiP20Pro.jpg",
    ondes: 22,
    deee: 0.3,
    classeEnergie: "A",
    label: "",
    note: 34
  },
  {
    id: 3,
    designation: "Téléphone3",
    fabricant: "Huawei",
    categorie: "smartphone",
    prixTTC: 850,
    batterie: "24",
    image: "images/HuaweiP20Pro.jpg",
    ondes: 22,
    deee: 0.3,
    classeEnergie: "A",
    label: "",
    note: 34
  },
  {
    id: 4,
    designation: "Téléphone4",
    fabricant: "Huawei",
    categorie: "smartphone",
    prixTTC: 850,
    batterie: "24",
    image: "images/HuaweiP20Pro.jpg",
    ondes: 22,
    deee: 0.3,
    classeEnergie: "A",
    label: "",
    note: 34
  },
  {
    id: 5,
    designation: "Asus T400S",
    fabricant: "Asus",
    categorie: "ordinateur",
    prixTTC: 400,
    batterie: "12",
    image: "images/asus.jpg",
    ondes: undefined,
    deee: 0.9,
    classeEnergie: "B",
    label: "label2",
    note: 50
  },
  {
    id: 6,
    designation: "Lenovo T430s",
    fabricant: "Lenovo",
    categorie: "ordinateur",
    prixTTC: 600,
    batterie: "6",
    image: "images/lenovoT430s.jpg",
    ondes: undefined,
    deee: 1.9,
    classeEnergie: "A",
    label: "label3",
    note: 56
  },
  {
    id: 7,
    designation: "Ordinateur3",
    fabricant: "Lenovo",
    categorie: "ordinateur",
    prixTTC: 600,
    batterie: "6",
    image: "images/lenovoT430s.jpg",
    ondes: undefined,
    deee: 1.9,
    classeEnergie: "A",
    label: "label3",
    note: 56
  },
  {
    id: 8,
    designation: "Ordinateur4",
    fabricant: "Lenovo",
    categorie: "ordinateur",
    prixTTC: 600,
    batterie: "6",
    image: "images/lenovoT430s.jpg",
    ondes: undefined,
    deee: 1.9,
    classeEnergie: "A",
    label: "label3",
    note: 56
  }

]